name: "Pull Request Validation"

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  install-dependencies:
    name: ðŸ’¾ Install Dependencies
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Install Dependencies and pre-cache
        uses: ./.github/actions/setup-node-pnpm

  quality-checks:
    needs: install-dependencies
    uses: ./.github/workflows/_quality-checks.yaml

  build:
    needs:
      - install-dependencies
      - quality-checks
    uses: ./.github/workflows/_build.yaml
